### ISSUE TITLE
Updated fork for Laravel 10

### ISSUE THREAD

**Issue by PascaleBeier** [mallardduck/blade-lucide-icons#3]
Hey Dan, thanks for your hard work! I hope you are doing well.

We revived this project under the fork https://github.com/Technikermathe/blade-lucide-icons with updated Lucide Icon and Laravel support.

**Comment by PascaleBeier** [comment]
We are open to do so!

**Comment by mallardduck** [comment]
Never saw a PR for this, IMO there's never anything wrong with submitting a PR to fix an issue you file. 
I would have totally merged the PR much sooner, but I just updated for 10 and 11.
