### ISSUE TITLE
Improvement suggestion

### ISSUE THREAD

**Issue by maqden** [mallardduck/blade-lucide-icons#4]
Hello

This package for working with Lucide icons is incredible!

It would be really cool if there could be a way to call the icons this way!

```
<x-lucide icon="album" />
```

I suggest this, because when we work with blade components, we create components by this way!

```
<li>
     <a href="{{ $route }}">
         <x-lucide :icon="$icon" />
         <span>{{ $label }}</span>
     </a>
</li>
```

**Comment by mallardduck** [comment]
Thanks for the reply on this @martinsnajdr! Spot on.
@maqden - as for your request, you need to submit that to https://github.com/blade-ui-kit/blade-icons

As this (and many other blade icon packages) simply inherit the behaviour of that package. So the functionality you're requesting is actually housed "upstream" in that package. This is not something I would want to maintain within just one of my many blade-icon family of packages.
